name: yummi_go
description: "A new Flutter project."
publish_to: 'none' # 'publish_to: none' yayınlamayı önler.

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API İstekleri ve Çerez Yönetimi için
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  # Standart Flutter ikonu
  cupertino_icons: ^1.0.6

  # Ses Tanıma Paketi
  speech_to_text: ^6.6.1
  provider: ^6.1.4

  # HTTP paketi Dio ile birlikte kullanılıyorsa gereksiz olabilir.
  # Eğer ApiService sadece Dio kullanıyorsa ve http başka bir yerde
  # kullanılmıyorsa, bu satırı silebilirsiniz. Şimdilik bırakıyorum.
  # Eğer sadece Dio kullanacaksanız silin:
  # http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Asset veya font eklemek isterseniz aşağıdaki bölümleri açabilirsiniz:
  # assets:
  #   - images/
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: fonts/MyCustomFont-Regular.ttf